apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-volume
  namespace: nginx
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /Users/edoatley/code/simple-nginx
  storageClassName: hostpath