apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-volume-claim
  namespace: nginx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 1Gi
  volumeName: nginx-volume